parallel = false

[dev]
tasks = ["dev-css", "dev-zola"]

[dev-css]
command = "echo css"
depends = ["dep1"]

[dev-zola]
command = "echo zola"
depends = ["dep2"]

[dep1]
command = "echo dep1"

[dep2]
command = "echo dep2"
