[workspace]
resolver = "3"
members = [
    "crates/braise-core",
    "crates/braise-errors",
    "crates/braise-types",
    "crates/braise-parser",
    "crates/braise-lexer",
    "crates/braise-runtime",
    "crates/braise-cli",
    "crates/braise-lsp",
    "crates/braise-fmt",
    "crates/braise-cache",
    "crates/braise-tests",
    "crates/logos-display",
    "crates/braise-bench",
]

[workspace.package]
version = "0.3.2-dev"
edition = "2024"
authors = ["cstef <hi@cstef.dev>"]
homepage = "https://github.com/cestef/braise"
description = "Yet another task runner, because apparently the world needed one more"
repository = "https://github.com/cestef/braise"

[workspace.dependencies]
miette = { version = "7.6.0", features = ["fancy"] }
owo-colors = "4.2.2"
logos = { git = "https://github.com/maciejhirsz/logos.git", rev = "274c7a0" }
log = "0.4"
env_logger = "0.11"
tokio = { version = "1", features = ["io-std", "macros", "rt-multi-thread"] }
bincode = "2"

[profile.dev]
incremental = true
codegen-units = 16
opt-level = 0

[profile.release]
opt-level = "z"
debug = false
lto = "fat"
panic = "abort"
codegen-units = 1

[profile.dist]
inherits = "release"
