[workspace]
package.version = "0.1.0"
package.edition = "2024"
package.authors = ["cstef <hi@cstef.dev>"]
resolver = "3"

members = [
    "crates/braise-core",
    "crates/braise-parser",
    "crates/braise-lexer",
    "crates/braise-runtime",
    "crates/braise-cli",
    "crates/braise-lsp",
    "crates/braise-fmt",
    "crates/logos-display",
]

[workspace.dependencies]
miette = { version = "7.6.0", features = ["fancy", "syntect-highlighter"] }
owo-colors = "4.2.2"
thiserror = "2.0.12"
logos = { git = "https://github.com/maciejhirsz/logos.git", rev = "274c7a0" }
tracing = { version = "0.1", features = ["std"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
