[package]
name = "braise-cli"
edition.workspace = true
version.workspace = true
authors.workspace = true

[dependencies]
clap = { version = "4.5.40", features = ["cargo"] }
miette.workspace = true
thiserror.workspace = true
logos.workspace = true

core = { path = "../braise-core", package = "braise-core" }
parser = { path = "../braise-parser", package = "braise-parser" }
lexer = { path = "../braise-lexer", package = "braise-lexer" }
runtime = { path = "../braise-runtime", package = "braise-runtime" }

[[bin]]
name = "braise"
path = "src/main.rs"
