[package]
name = "braise-tests"
description = "Tests for braisé"
edition.workspace = true
version.workspace = true
authors.workspace = true
publish = false

[dependencies]
braise-lexer = { path = "../braise-lexer" }
braise-parser = { path = "../braise-parser" }
braise-runtime = { path = "../braise-runtime" }
core = { path = "../braise-core", package = "braise-core" }
