[package]
name = "braise-parser"
edition.workspace = true
version.workspace = true
authors.workspace = true

[dependencies]
miette.workspace = true
thiserror.workspace = true
tracing.workspace = true

lexer = { path = "../braise-lexer", package = "braise-lexer" }
core = { path = "../braise-core", package = "braise-core" }
