[package]
name = "braise-parser"
edition.workspace = true
version.workspace = true
authors.workspace = true

[dependencies]
braise-errors = { path = "../braise-errors" }
miette.workspace = true
log.workspace = true

lexer = { path = "../braise-lexer", package = "braise-lexer" }
core = { path = "../braise-core", package = "braise-core" }

[dev-dependencies]

