[package]
name = "braise-lsp"
description = "Language Server Protocol implementation for braisé"
edition.workspace = true
version.workspace = true
authors.workspace = true

[dependencies]
tower-lsp = "0.20.0"
ropey = "1"
url = "2.4"
regex = { version = "0.1", package = "regex-lite" }

log.workspace = true
env_logger.workspace = true
tokio.workspace = true
miette.workspace = true

braise-core = { path = "../braise-core", package = "braise-core" }
lexer = { path = "../braise-lexer", package = "braise-lexer" }
parser = { path = "../braise-parser", package = "braise-parser" }
fmt = { path = "../braise-fmt", package = "braise-fmt" }
runtime = { path = "../braise-runtime", package = "braise-runtime" }
braise-errors = { path = "../braise-errors" }
