[package]
name = "braise-types"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
miette.workspace = true
thiserror.workspace = true
owo-colors.workspace = true
serde = { version = "1.0", features = ["derive"] }

braise-errors = { path = "../braise-errors" }
